name = "AAS247Julia"

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
DrWatson = "2.19.1"
HypertextLiteral = "0.9"
Pluto = "0.20.20"
PlutoUI = "0.7"
Revise = "3"
julia = "1.11.7"
